# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xZXd0i8ko3oh156Os8kyRjKNnuQ7xIJN
"""

import numpy as np
import csv
import copy

y = np.array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2])

import sys
path = str(sys.argv[1])
X = np.genfromtxt(path, delimiter='\t')

y = y.astype(np.int64)
X = X.astype(np.int64)
X0 = copy.deepcopy(X)

# Do the Permutations
# Accuracy
X = copy.deepcopy(X0)
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy0 = count / 150 * 100
#accuracy0

X = copy.deepcopy(X0)
for i in range(150):
  if (X[i] == 1):
    X[i] = 2
  elif (X[i] == 2):
    X[i] = 1


#Accuracy
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy1 = count / 150 * 100
#accuracy1

X = copy.deepcopy(X0)
for i in range(150):
  if (X[i] == 1):
    X[i] = 0
  elif (X[i] == 0):
    X[i] = 1

#Accuracy
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy2 = count / 150 * 100
#accuracy2

X = copy.deepcopy(X0)
for i in range(150):
  if (X[i] == 0):
    X[i] = 1
  elif (X[i] == 1):
    X[i] = 2
  elif (X[i] == 2):
    X[i] = 0

#Accuracy
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy3 = count / 150 * 100
#accuracy3

X = copy.deepcopy(X0)
for i in range(150):
  if (X[i] == 0):
    X[i] = 2
  elif (X[i] == 1):
    X[i] = 0
  elif (X[i] == 2):
    X[i] = 1

#Accuracy
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy4 = count / 150 * 100
#accuracy4

X = copy.deepcopy(X0)
for i in range(150):
  if (X[i] == 0):
    X[i] = 2
  elif (X[i] == 1):
    X[i] = 1
  elif (X[i] == 2):
    X[i] = 0

#Accuracy
count = 0
for i in range(0, 150):
  if (y[i] == X[i]):
    count = count + 1

accuracy5 = count / 150 * 100
#accuracy5

accuracy = max(accuracy0, accuracy1, accuracy2, accuracy3, accuracy4, accuracy5)
print("Accuracy = " + str(accuracy))